sudo: false

language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "tztZE419tCIn8SqrGPTO0KYUqHacsWG417bX4yEFEiuAalLtfDnQapEb01fF2yAZhqSalkSDWurI3eJlHbY7cxhkDFrytJzxKEF9x7yn7Fz5eF3fLO42GUgZUhqQIghDBzLPjL5GwWCJF9Bl4czRigBFQMvP5PqXbeOFTjoiWaV9kowB+p8q+PzKcKHMRd0+IN6RmlapC9ObX7pXtPfB8IbW6dU+iJcVXTMaixQbulJ+73uc9ZXouV9qTGJRUeITTzuXwPsbTMi2DBU2HtWn16PHCZOXZuRkjgSOx5/eCPkewoO59yv8VHxUtZKFrWBDFtJsIyyDaPIze64kpaDkaNsj3V0fXtjIFNGt1Py8Ndej8nD1JEOx38JaoKN8BpmESZ+I26/H0YOBC9OJqGHii6lAAXVJpQH2R54VvpO9shjuWoI5tLyCMqLtfAJ5z6kbiU/xfjBx2qSZWn1TNrhpsPpGIm8CorwYATmKidZsb6/MAAoMEEzwzamjVSzmc8Eyxd4yAU4kbp2hEnNDYdcve3obBfoW8hZZJeTTrX4dPDJva4axi6C96i/6hO3rgnIf0OO2xkQkens7lkDS4oBNgVHvCpx5gMav/dyj5DFpmhAnvxhCvn1Ku8Fk16vZMnOS2Yj/hAdiRxpuzAm4nIrnXOH1O6Kv7qlm9lwdJ3me1jA="
cache:
  directories:
    - $HOME/.m2

script:
  - "mvn cobertura:cobertura"
  - "mvn javadoc:javadoc"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash Deploy_JavaDoc.sh

notification:
  email:
    on_success: never
    on_failure: always